# Hardware configuration for pero (MacBook Pro 13" 2017)
# This is a PLACEHOLDER configuration for initial setup
#
# IMPORTANT: When installing NixOS on the MacBook, replace this file with
# the actual hardware-configuration.nix generated by nixos-generate-config
#
# To generate the actual hardware configuration on pero, run:
#   sudo nixos-generate-config --show-hardware-config > /tmp/hardware-config.nix
#
# Then copy it to: hosts/pero/hardware-configuration.nix

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/hardware/network/broadcom-43xx.nix")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  # System platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Placeholder configuration based on typical MacBook Pro 13" 2017 specs
  # MacBook Pro 13" 2017 typically has:
  # - Intel Core i5/i7 (7th gen Kaby Lake)
  # - 256GB or 512GB NVMe SSD
  # - 8GB or 16GB RAM
  # - Intel Iris Plus Graphics 640/650

  boot.initrd.availableKernelModules = [
    "xhci_pci" # USB 3.0
    "ahci" # SATA
    "nvme" # NVMe SSD
    "usb_storage" # USB storage
    "sd_mod" # SD card
    "sdhci_pci" # SD host controller
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  # Note: If you need Broadcom WiFi driver, you may need to enable broadcom_sta
  # and add it to permittedInsecurePackages (see nixpkgs.config.permittedInsecurePackages)

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0b6e04e5-52cc-4fa5-a72f-6d11555638ee";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5F66-17ED";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/69d9f2cf-bb0a-438e-b9ff-d1a772f09a76"; }
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Graphics drivers
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # For hardware acceleration
      intel-vaapi-driver # VA-API driver for Intel
      libva-vdpau-driver # VDPAU driver
      libvdpau-va-gl # VDPAU backend for VA-GL
    ];
  };

  # Network hardware
  # Broadcom WiFi is common in MacBooks - may need additional firmware
  hardware.enableRedistributableFirmware = true;

  # High resolution display
  # MacBook Pro 13" 2017 has a 2560x1600 Retina display
  services.xserver.videoDrivers = [ "intel" ];
}
