# secrets/.sops.yaml
keys:
  # Replace this with the public key from ~/.config/sops/age/keys.txt
  - &user_key "age1..."

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user_key